/**
 * Created by liuxin on 2017/8/9.
 */
// export const SET_APPLE_ADD = 'SET_APPLE_ADD';
export const SET_APPLE_ADD_PRICE = 'SET_APPLE_ADD_PRICE';
export const SET_APPLE_ADD_WEIGHT = 'SET_APPLE_ADD_WEIGHT';

export const SET_APPLE_SUBTRACT_PRICE = 'SET_APPLE_SUBTRACT_PRICE';
export const SET_APPLE_SUBTRACT_WEIGHT = 'SET_APPLE_SUBTRACT_WEIGHT';
// export const SET_APPLE_SUBTRACT = 'SET_APPLE_SUBTRACT';

export const SET_BANANA_ADD_PRICE = 'SET_BANANA_ADD_PRICE';
export const SET_BANANA_ADD_WEIGHT = 'SET_BANANA_ADD_WEIGHT';
// export const SET_BANANA_ADD = 'SET_BANANA_ADD';

export const SET_BANANA_SUBTRACT_PRICE = 'SET_BANANA_SUBTRACT_PRICE';
export const SET_BANANA_SUBTRACT_WEIGHT = 'SET_BANANA_SUBTRACT_WEIGHT';
// export const SET_BANANA_SUBTRACT = 'SET_BANANA_SUBTRACT';
